[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -p no:warnings
env =
    FLASK_ENV=testing
    FLASK_APP=app
    DATABASE_URL=sqlite:///test.db
    SECRET_KEY=test_key
    JWT_SECRET_KEY=test_jwt_key